Quotes_Project/config/routes.rb
Rails.application.routes.draw do

  devise_for :customers

  root to: "customer_profile#index"

devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

    match ':controller(/:action(/:id))',:via => [:get,:post]

end

Quotes_Project/app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :name
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Quotes_Project/app/models/customer_profile.rb
class CustomerProfile < ActiveRecord::Base
end

Quotes_Project/app/models/product.rb
class Product < ActiveRecord::Base
end

Quotes_Project/app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
end

Quotes_Project/app/models/supplier_profile.rb
class SupplierProfile < ActiveRecord::Base
end

Quotes_Project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:address,:phone_no,:state,:email,:password,:confirm_password])
 end
end

Quotes_Project/app/controllers/customer_profile_controller.rb
class CustomerProfileController < ApplicationController
  def index
  end

  def show
  end
end

Quotes_Project/app/helpers/application_helper.rb
module ApplicationHelper
end

Quotes_Project/app/helpers/customer_profile_helper.rb
module CustomerProfileHelper
end

Quotes_Project/app/views/customer_profile/index.html.erb
<% if customer_signed_in? %>
     <div class="back">
     <!-- user can logout after seeing the the details of the subject -->
          <br><br><br>  <%= link_to('Logout', destroy_customer_session_path, :method => :delete, :style => "color:cyan;margin-left:100px;font-size:20px") %></div>
<%end%>

Quotes_Project/app/views/customer_profile/show.html.erb
<h1>CustomerProfile#show</h1>
<p>Find me in app/views/customer_profile/show.html.erb</p>

Quotes_Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuotesProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>